# Generated by Django 3.0.6 on 2020-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoweb', '0002_auto_20201228_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
