# Generated by Django 3.0.6 on 2020-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoweb', '0003_userprofile_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bio',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='static/profile_image'),
        ),
    ]
