# Generated by Django 3.0.6 on 2020-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoweb', '0004_auto_20201228_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bio',
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='static/profile_image'),
        ),
    ]
