# Generated by Django 3.0.6 on 2020-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoweb', '0006_auto_20201228_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_image'),
        ),
    ]
