# Generated by Django 3.0.6 on 2020-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoweb', '0008_auto_20201228_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_topic', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
