# Generated by Django 3.0.6 on 2020-12-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoweb', '0009_picturepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturepost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoweb.UserProfile'),
        ),
    ]
